# Generated by Django 5.1.7 on 2025-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('distance', 'Дистанционный'), ('full-time', 'Очный')], default='distance', max_length=10),
        ),
    ]
