# Generated by Django 5.1.7 on 2025-03-20 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_mentor_teacher_usefulpost_lab_lectures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.JSONField()),
                ('href', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='app.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Lectures',
        ),
    ]
